### ISSUE TITLE
Doctrine Relationship

### ISSUE THREAD

**Issue by MatthieuMota** [Grafikart/BlogMVC-Symfony3#2]
Hey @Grafikart !
About your entites repositories, I think you can save time. With Doctrine, you can lazy & easy fetch related object (http://symfony.com/doc/current/doctrine/associations.html#fetching-related-objects).
You can also access to this related object in Twig ! You don't need query builder for generic queries !
Example with Post and Category:
```
$post = $this->getDoctrine()
        ->getRepository('AppBundle:Post')
        ->find(10);
var_dump($post->getCategories());
```
In Twig:
```
{% for category in post.categories %}
    {{ category }}
{% endfor %}
```
You can easily reverse that !
```
$categorie = $this->getDoctrine()
        ->getRepository('AppBundle:Category')
        ->find(5);
$categorie->getPosts();
``` 
The only required thing is to define property and getter/setter in your entities ;)
Closer to laravel in this way ? :)

**Comment by Grafikart** [comment]
This strategy does a lot of SQL queries. If I list 10 post and "lazy" load category in twig it could do 11 queries (this is the n+1 problem I was trying to avoid).

**Comment by MatthieuMota** [comment]
Ok I just saw this in your readme. I understand better if it's a performance issue ! I see in #1 that you also saw eager fetch mode.
